import libs = magic_enum%lib{magic_enum}

cxx.poptions += "-I$src_root/3rdparty/Catch2"

./: exe{driver_test}: test/{cxx}{test} $src_root/3rdparty/Catch2/hxx{**} $libs
./: exe{driver_test_flags}: test/{cxx}{test_flags} $src_root/3rdparty/Catch2/hxx{**} $libs
