import libs = magic_enum%lib{magic_enum}
import libs += catch2%lib{catch2}

for t : tests_src/cxx{* -test_nonascii}
{
  n = $name($t)
  ./: exe{$n}: $t tests_src/hxx{**} $libs
}

./: exe{test_nonascii}: include = ($cxx.id == 'gcc')
exe{test_nonascii}: tests_src/cxx{test_nonascii} tests_src/hxx{**} $libs
